package entities;

public enum CommandType {
    No_COMMAND,
    SELECT_NEW_RESTAURANT,
    VIEW_AVAILABLE_INGREDIENTS,
    VIEW_TOTAL_SALES,
    VIEW_TOTAL_EXPENSE,
    VIEW_NET_PROFIT,
    PLACE_ORDER,
    ORDER_SPECIFIC_INGREDIENTS,
    OPEN_NEW_RESTAURANT,
    EXIT,
    ORDER_MULTIPLE_INGREDIENTS,
    FINALISE_ORDER,
    CLOSE_RESTAURANT,
    INPUT_INGREDIENT_QTY;
}
